/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects */
        get: operations["listProjects"];
        put?: never;
        /** Create project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{projectId}/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List project groups */
        get: operations["listProjectGroups"];
        put?: never;
        /** Add group to project */
        post: operations["addProjectGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove group from project */
        delete: operations["deleteProjectGroup"];
        options?: never;
        head?: never;
        /** Update project group role */
        patch: operations["updateProjectGroup"];
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List groups */
        get: operations["listGroups"];
        put?: never;
        /** Create group */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        /** Delete group */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        /** Update group */
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group members */
        get: operations["listGroupMembers"];
        put?: never;
        /** Add user to group */
        post: operations["addGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove user from group */
        delete: operations["deleteGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kanban board snapshot */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tickets for project */
        get: operations["listTickets"];
        put?: never;
        /** Create ticket */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ticket */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        /** Delete ticket */
        delete: operations["deleteTicket"];
        options?: never;
        head?: never;
        /** Update ticket */
        patch: operations["updateTicket"];
        trace?: never;
    };
    "/projects/{projectId}/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stories */
        get: operations["listStories"];
        put?: never;
        /** Create story */
        post: operations["createStory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get story */
        get: operations["getStory"];
        put?: never;
        post?: never;
        /** Delete story */
        delete: operations["deleteStory"];
        options?: never;
        head?: never;
        /** Update story */
        patch: operations["updateStory"];
        trace?: never;
    };
    "/tickets/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ticket comments */
        get: operations["listTicketComments"];
        put?: never;
        /** Add ticket comment */
        post: operations["addTicketComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete ticket comment */
        delete: operations["deleteTicketComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get workflow states */
        get: operations["getWorkflow"];
        /** Update workflow states */
        put: operations["updateWorkflow"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhooks */
        get: operations["listWebhooks"];
        put?: never;
        /** Create webhook */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get webhook */
        get: operations["getWebhook"];
        put?: never;
        post?: never;
        /** Delete webhook */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        /** Update webhook */
        patch: operations["updateWebhook"];
        trace?: never;
    };
    "/projects/{projectId}/webhooks/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send test webhook */
        post: operations["testWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        AuthLoginRequest: {
            /** @description Email or username */
            identifier?: string;
            /**
             * Format: email
             * @deprecated
             */
            email?: string;
            /** @deprecated */
            username?: string;
            /** Format: password */
            password: string;
        };
        AuthLoginResponse: {
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        UserSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email?: string;
        };
        UserListResponse: {
            items: components["schemas"]["UserSummary"][];
        };
        /**
         * @description 4-character uppercase alphanumeric project key.
         * @example PROJ
         */
        ProjectKey: string;
        /**
         * @description Ticket key in format PROJECT-###, where
         * @example PROJ-001
         */
        TicketKey: string;
        /** @enum {string} */
        ProjectRole: "admin" | "contributor" | "viewer";
        /** @enum {string} */
        ProjectPermission: "read" | "create" | "update" | "delete" | "admin";
        Project: {
            /** Format: uuid */
            id: string;
            key: components["schemas"]["ProjectKey"];
            name: string;
            description?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectCreateRequest: {
            key: components["schemas"]["ProjectKey"];
            name: string;
            description?: string;
        };
        ProjectUpdateRequest: {
            name?: string;
            description?: string;
        };
        ProjectListResponse: {
            items: components["schemas"]["Project"][];
        };
        Group: {
            /** Format: uuid */
            id: string;
            name: string;
            description?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GroupCreateRequest: {
            name: string;
            description?: string;
        };
        GroupUpdateRequest: {
            name?: string;
            description?: string;
        };
        GroupListResponse: {
            items: components["schemas"]["Group"][];
        };
        GroupMember: {
            /** Format: uuid */
            groupId: string;
            /** Format: uuid */
            userId: string;
            user?: components["schemas"]["UserSummary"];
        };
        GroupMemberCreateRequest: {
            /** Format: uuid */
            userId: string;
        };
        GroupMemberListResponse: {
            items: components["schemas"]["GroupMember"][];
        };
        ProjectGroup: {
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            groupId: string;
            role: components["schemas"]["ProjectRole"];
            permissions: components["schemas"]["ProjectPermission"][];
        };
        ProjectGroupCreateRequest: {
            /** Format: uuid */
            groupId: string;
            role: components["schemas"]["ProjectRole"];
        };
        ProjectGroupUpdateRequest: {
            role: components["schemas"]["ProjectRole"];
        };
        ProjectGroupListResponse: {
            items: components["schemas"]["ProjectGroup"][];
        };
        WorkflowState: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            order: number;
            isDefault: boolean;
            isClosed: boolean;
        };
        WorkflowStateInput: {
            /** Format: uuid */
            id?: string;
            name: string;
            order: number;
            isDefault: boolean;
            isClosed: boolean;
        };
        WorkflowResponse: {
            states: components["schemas"]["WorkflowState"][];
        };
        WorkflowUpdateRequest: {
            states: components["schemas"]["WorkflowStateInput"][];
        };
        /** @enum {string} */
        TicketPriority: "low" | "medium" | "high" | "urgent";
        /** @enum {string} */
        TicketType: "feature" | "bug";
        Story: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            title: string;
            description?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StoryCreateRequest: {
            title: string;
            description?: string;
        };
        StoryUpdateRequest: {
            title?: string;
            description?: string;
        };
        StoryListResponse: {
            items: components["schemas"]["Story"][];
        };
        TicketComment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ticketId: string;
            /** Format: uuid */
            authorId: string;
            authorName: string;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        TicketCommentCreateRequest: {
            message: string;
        };
        TicketCommentListResponse: {
            items: components["schemas"]["TicketComment"][];
        };
        Ticket: {
            /** Format: uuid */
            id: string;
            key: components["schemas"]["TicketKey"];
            number: number;
            type: components["schemas"]["TicketType"];
            /** Format: uuid */
            projectId: string;
            projectKey: components["schemas"]["ProjectKey"];
            /** Format: uuid */
            storyId?: string | null;
            story?: components["schemas"]["Story"];
            title: string;
            description?: string;
            /** Format: uuid */
            stateId: string;
            state?: components["schemas"]["WorkflowState"];
            /** Format: uuid */
            assigneeId?: string | null;
            assignee?: components["schemas"]["UserSummary"];
            priority: components["schemas"]["TicketPriority"];
            /** Format: float */
            position: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TicketCreateRequest: {
            title: string;
            description?: string;
            type?: components["schemas"]["TicketType"];
            /** Format: uuid */
            storyId?: string | null;
            /** Format: uuid */
            stateId?: string;
            /** Format: uuid */
            assigneeId?: string | null;
            priority?: components["schemas"]["TicketPriority"];
        };
        TicketUpdateRequest: {
            title?: string;
            description?: string;
            type?: components["schemas"]["TicketType"];
            /** Format: uuid */
            storyId?: string | null;
            /** Format: uuid */
            stateId?: string;
            /** Format: uuid */
            assigneeId?: string | null;
            priority?: components["schemas"]["TicketPriority"];
            /** Format: float */
            position?: number;
        };
        TicketListResponse: {
            items: components["schemas"]["Ticket"][];
            total: number;
        };
        BoardResponse: {
            project: components["schemas"]["Project"];
            states: components["schemas"]["WorkflowState"][];
            tickets: components["schemas"]["Ticket"][];
        };
        /** @enum {string} */
        WebhookEvent: "ticket.created" | "ticket.updated" | "ticket.deleted" | "ticket.state_changed";
        Webhook: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uri */
            url: string;
            events: components["schemas"]["WebhookEvent"][];
            enabled: boolean;
            secret?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WebhookCreateRequest: {
            /** Format: uri */
            url: string;
            events: components["schemas"]["WebhookEvent"][];
            enabled?: boolean;
            secret?: string;
        };
        WebhookUpdateRequest: {
            /** Format: uri */
            url?: string;
            events?: components["schemas"]["WebhookEvent"][];
            enabled?: boolean;
            secret?: string;
        };
        WebhookListResponse: {
            items: components["schemas"]["Webhook"][];
        };
        WebhookTestRequest: {
            event?: components["schemas"]["WebhookEvent"];
            /** Format: uuid */
            ticketId?: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        WebhookTestResponse: {
            delivered: boolean;
            statusCode?: number;
            responseBody?: string;
        };
        ErrorResponse: {
            error: string;
            message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Search by name or email */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdateRequest"];
            };
        };
        responses: {
            /** @description Project updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    listProjectGroups: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project group list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGroupListResponse"];
                };
            };
        };
    };
    addProjectGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectGroupCreateRequest"];
            };
        };
        responses: {
            /** @description Project group added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGroup"];
                };
            };
        };
    };
    deleteProjectGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProjectGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectGroupUpdateRequest"];
            };
        };
        responses: {
            /** @description Project group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGroup"];
                };
            };
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupListResponse"];
                };
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupCreateRequest"];
            };
        };
        responses: {
            /** @description Group created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupUpdateRequest"];
            };
        };
        responses: {
            /** @description Group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
        };
    };
    listGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group member list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMemberListResponse"];
                };
            };
        };
    };
    addGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupMemberCreateRequest"];
            };
        };
        responses: {
            /** @description Group member created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"];
                };
            };
        };
    };
    deleteGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Board */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardResponse"];
                };
            };
        };
    };
    listTickets: {
        parameters: {
            query?: {
                stateId?: string;
                assigneeId?: string;
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                };
            };
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreateRequest"];
            };
        };
        responses: {
            /** @description Ticket created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdateRequest"];
            };
        };
        responses: {
            /** @description Ticket updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
        };
    };
    listStories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Story list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryListResponse"];
                };
            };
        };
    };
    createStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryCreateRequest"];
            };
        };
        responses: {
            /** @description Story created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
        };
    };
    getStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Story */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
        };
    };
    deleteStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateStory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryUpdateRequest"];
            };
        };
        responses: {
            /** @description Story updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
        };
    };
    listTicketComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketCommentListResponse"];
                };
            };
        };
    };
    addTicketComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCommentCreateRequest"];
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketComment"];
                };
            };
        };
    };
    deleteTicketComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workflow */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
        };
    };
    updateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdateRequest"];
            };
        };
        responses: {
            /** @description Workflow updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowResponse"];
                };
            };
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookListResponse"];
                };
            };
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreateRequest"];
            };
        };
        responses: {
            /** @description Webhook created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
        };
    };
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookUpdateRequest"];
            };
        };
        responses: {
            /** @description Webhook updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Webhook"];
                };
            };
        };
    };
    testWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookTestRequest"];
            };
        };
        responses: {
            /** @description Test result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookTestResponse"];
                };
            };
        };
    };
}
