// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package httpapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	SessionAuthScopes = "sessionAuth.Scopes"
)

// Defines values for ProjectPermission.
const (
	ProjectPermissionAdmin  ProjectPermission = "admin"
	ProjectPermissionCreate ProjectPermission = "create"
	ProjectPermissionDelete ProjectPermission = "delete"
	ProjectPermissionRead   ProjectPermission = "read"
	ProjectPermissionUpdate ProjectPermission = "update"
)

// Defines values for ProjectRole.
const (
	ProjectRoleAdmin       ProjectRole = "admin"
	ProjectRoleContributor ProjectRole = "contributor"
	ProjectRoleViewer      ProjectRole = "viewer"
)

// Defines values for TicketPriority.
const (
	High   TicketPriority = "high"
	Low    TicketPriority = "low"
	Medium TicketPriority = "medium"
	Urgent TicketPriority = "urgent"
)

// Defines values for TicketType.
const (
	Bug     TicketType = "bug"
	Feature TicketType = "feature"
)

// Defines values for WebhookEvent.
const (
	TicketCreated      WebhookEvent = "ticket.created"
	TicketDeleted      WebhookEvent = "ticket.deleted"
	TicketStateChanged WebhookEvent = "ticket.state_changed"
	TicketUpdated      WebhookEvent = "ticket.updated"
)

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Email *openapi_types.Email `json:"email,omitempty"`

	// Identifier Email or username
	Identifier *string `json:"identifier,omitempty"`
	Password   string  `json:"password"`
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	Username *string `json:"username,omitempty"`
}

// AuthLoginResponse defines model for AuthLoginResponse.
type AuthLoginResponse struct {
	User User `json:"user"`
}

// BoardResponse defines model for BoardResponse.
type BoardResponse struct {
	Project Project         `json:"project"`
	States  []WorkflowState `json:"states"`
	Tickets []Ticket        `json:"tickets"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string  `json:"error"`
	Message *string `json:"message,omitempty"`
}

// Group defines model for Group.
type Group struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// GroupCreateRequest defines model for GroupCreateRequest.
type GroupCreateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// GroupListResponse defines model for GroupListResponse.
type GroupListResponse struct {
	Items []Group `json:"items"`
}

// GroupMember defines model for GroupMember.
type GroupMember struct {
	GroupId openapi_types.UUID `json:"groupId"`
	User    *UserSummary       `json:"user,omitempty"`
	UserId  openapi_types.UUID `json:"userId"`
}

// GroupMemberCreateRequest defines model for GroupMemberCreateRequest.
type GroupMemberCreateRequest struct {
	UserId openapi_types.UUID `json:"userId"`
}

// GroupMemberListResponse defines model for GroupMemberListResponse.
type GroupMemberListResponse struct {
	Items []GroupMember `json:"items"`
}

// GroupUpdateRequest defines model for GroupUpdateRequest.
type GroupUpdateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`

	// Key 4-character uppercase alphanumeric project key.
	Key       ProjectKey `json:"key"`
	Name      string     `json:"name"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

// ProjectCreateRequest defines model for ProjectCreateRequest.
type ProjectCreateRequest struct {
	Description *string `json:"description,omitempty"`

	// Key 4-character uppercase alphanumeric project key.
	Key  ProjectKey `json:"key"`
	Name string     `json:"name"`
}

// ProjectGroup defines model for ProjectGroup.
type ProjectGroup struct {
	GroupId     openapi_types.UUID  `json:"groupId"`
	Permissions []ProjectPermission `json:"permissions"`
	ProjectId   openapi_types.UUID  `json:"projectId"`
	Role        ProjectRole         `json:"role"`
}

// ProjectGroupCreateRequest defines model for ProjectGroupCreateRequest.
type ProjectGroupCreateRequest struct {
	GroupId openapi_types.UUID `json:"groupId"`
	Role    ProjectRole        `json:"role"`
}

// ProjectGroupListResponse defines model for ProjectGroupListResponse.
type ProjectGroupListResponse struct {
	Items []ProjectGroup `json:"items"`
}

// ProjectGroupUpdateRequest defines model for ProjectGroupUpdateRequest.
type ProjectGroupUpdateRequest struct {
	Role ProjectRole `json:"role"`
}

// ProjectKey 4-character uppercase alphanumeric project key.
type ProjectKey = string

// ProjectListResponse defines model for ProjectListResponse.
type ProjectListResponse struct {
	Items []Project `json:"items"`
}

// ProjectPermission defines model for ProjectPermission.
type ProjectPermission string

// ProjectRole defines model for ProjectRole.
type ProjectRole string

// ProjectUpdateRequest defines model for ProjectUpdateRequest.
type ProjectUpdateRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// Story defines model for Story.
type Story struct {
	CreatedAt   time.Time          `json:"createdAt"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	ProjectId   openapi_types.UUID `json:"projectId"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updatedAt"`
}

// StoryCreateRequest defines model for StoryCreateRequest.
type StoryCreateRequest struct {
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// StoryListResponse defines model for StoryListResponse.
type StoryListResponse struct {
	Items []Story `json:"items"`
}

// StoryUpdateRequest defines model for StoryUpdateRequest.
type StoryUpdateRequest struct {
	Description *string `json:"description,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// SyncUsersResponse defines model for SyncUsersResponse.
type SyncUsersResponse struct {
	// Synced Number of users synced
	Synced int `json:"synced"`

	// Total Total users in Keycloak
	Total int `json:"total"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	Assignee    *UserSummary        `json:"assignee,omitempty"`
	AssigneeId  *openapi_types.UUID `json:"assigneeId"`
	CreatedAt   time.Time           `json:"createdAt"`
	Description *string             `json:"description,omitempty"`
	Id          openapi_types.UUID  `json:"id"`

	// Key Ticket key in format PROJECT-###, where
	Key       TicketKey          `json:"key"`
	Number    int                `json:"number"`
	Position  float32            `json:"position"`
	Priority  TicketPriority     `json:"priority"`
	ProjectId openapi_types.UUID `json:"projectId"`

	// ProjectKey 4-character uppercase alphanumeric project key.
	ProjectKey ProjectKey          `json:"projectKey"`
	State      *WorkflowState      `json:"state,omitempty"`
	StateId    openapi_types.UUID  `json:"stateId"`
	Story      *Story              `json:"story,omitempty"`
	StoryId    *openapi_types.UUID `json:"storyId"`
	Title      string              `json:"title"`
	Type       TicketType          `json:"type"`
	UpdatedAt  time.Time           `json:"updatedAt"`
}

// TicketComment defines model for TicketComment.
type TicketComment struct {
	AuthorId   openapi_types.UUID `json:"authorId"`
	AuthorName string             `json:"authorName"`
	CreatedAt  time.Time          `json:"createdAt"`
	Id         openapi_types.UUID `json:"id"`
	Message    string             `json:"message"`
	TicketId   openapi_types.UUID `json:"ticketId"`
}

// TicketCommentCreateRequest defines model for TicketCommentCreateRequest.
type TicketCommentCreateRequest struct {
	Message string `json:"message"`
}

// TicketCommentListResponse defines model for TicketCommentListResponse.
type TicketCommentListResponse struct {
	Items []TicketComment `json:"items"`
}

// TicketCreateRequest defines model for TicketCreateRequest.
type TicketCreateRequest struct {
	AssigneeId  *openapi_types.UUID `json:"assigneeId"`
	Description *string             `json:"description,omitempty"`
	Priority    *TicketPriority     `json:"priority,omitempty"`
	StateId     *openapi_types.UUID `json:"stateId,omitempty"`
	StoryId     *openapi_types.UUID `json:"storyId"`
	Title       string              `json:"title"`
	Type        *TicketType         `json:"type,omitempty"`
}

// TicketKey Ticket key in format PROJECT-###, where
type TicketKey = string

// TicketListResponse defines model for TicketListResponse.
type TicketListResponse struct {
	Items []Ticket `json:"items"`
	Total int      `json:"total"`
}

// TicketPriority defines model for TicketPriority.
type TicketPriority string

// TicketType defines model for TicketType.
type TicketType string

// TicketUpdateRequest defines model for TicketUpdateRequest.
type TicketUpdateRequest struct {
	AssigneeId  *openapi_types.UUID `json:"assigneeId"`
	Description *string             `json:"description,omitempty"`
	Position    *float32            `json:"position,omitempty"`
	Priority    *TicketPriority     `json:"priority,omitempty"`
	StateId     *openapi_types.UUID `json:"stateId,omitempty"`
	StoryId     *openapi_types.UUID `json:"storyId"`
	Title       *string             `json:"title,omitempty"`
	Type        *TicketType         `json:"type,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
}

// UserListResponse defines model for UserListResponse.
type UserListResponse struct {
	Items []UserSummary `json:"items"`
}

// UserSummary defines model for UserSummary.
type UserSummary struct {
	Email *openapi_types.Email `json:"email,omitempty"`
	Id    openapi_types.UUID   `json:"id"`
	Name  string               `json:"name"`
}

// Webhook defines model for Webhook.
type Webhook struct {
	CreatedAt time.Time          `json:"createdAt"`
	Enabled   bool               `json:"enabled"`
	Events    []WebhookEvent     `json:"events"`
	Id        openapi_types.UUID `json:"id"`
	ProjectId openapi_types.UUID `json:"projectId"`
	Secret    *string            `json:"secret,omitempty"`
	UpdatedAt time.Time          `json:"updatedAt"`
	Url       string             `json:"url"`
}

// WebhookCreateRequest defines model for WebhookCreateRequest.
type WebhookCreateRequest struct {
	Enabled *bool          `json:"enabled,omitempty"`
	Events  []WebhookEvent `json:"events"`
	Secret  *string        `json:"secret,omitempty"`
	Url     string         `json:"url"`
}

// WebhookEvent defines model for WebhookEvent.
type WebhookEvent string

// WebhookListResponse defines model for WebhookListResponse.
type WebhookListResponse struct {
	Items []Webhook `json:"items"`
}

// WebhookTestRequest defines model for WebhookTestRequest.
type WebhookTestRequest struct {
	Event    *WebhookEvent           `json:"event,omitempty"`
	Payload  *map[string]interface{} `json:"payload,omitempty"`
	TicketId *openapi_types.UUID     `json:"ticketId,omitempty"`
}

// WebhookTestResponse defines model for WebhookTestResponse.
type WebhookTestResponse struct {
	Delivered    bool    `json:"delivered"`
	ResponseBody *string `json:"responseBody,omitempty"`
	StatusCode   *int    `json:"statusCode,omitempty"`
}

// WebhookUpdateRequest defines model for WebhookUpdateRequest.
type WebhookUpdateRequest struct {
	Enabled *bool           `json:"enabled,omitempty"`
	Events  *[]WebhookEvent `json:"events,omitempty"`
	Secret  *string         `json:"secret,omitempty"`
	Url     *string         `json:"url,omitempty"`
}

// WorkflowResponse defines model for WorkflowResponse.
type WorkflowResponse struct {
	States []WorkflowState `json:"states"`
}

// WorkflowState defines model for WorkflowState.
type WorkflowState struct {
	Id        openapi_types.UUID `json:"id"`
	IsClosed  bool               `json:"isClosed"`
	IsDefault bool               `json:"isDefault"`
	Name      string             `json:"name"`
	Order     int                `json:"order"`
	ProjectId openapi_types.UUID `json:"projectId"`
}

// WorkflowStateInput defines model for WorkflowStateInput.
type WorkflowStateInput struct {
	Id        *openapi_types.UUID `json:"id,omitempty"`
	IsClosed  bool                `json:"isClosed"`
	IsDefault bool                `json:"isDefault"`
	Name      string              `json:"name"`
	Order     int                 `json:"order"`
}

// WorkflowUpdateRequest defines model for WorkflowUpdateRequest.
type WorkflowUpdateRequest struct {
	States []WorkflowStateInput `json:"states"`
}

// ListTicketsParams defines parameters for ListTickets.
type ListTicketsParams struct {
	StateId    *openapi_types.UUID `form:"stateId,omitempty" json:"stateId,omitempty"`
	AssigneeId *openapi_types.UUID `form:"assigneeId,omitempty" json:"assigneeId,omitempty"`
	Q          *string             `form:"q,omitempty" json:"q,omitempty"`
	Limit      *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int                `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Q Search by name or email
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = AuthLoginRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = GroupCreateRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = GroupUpdateRequest

// AddGroupMemberJSONRequestBody defines body for AddGroupMember for application/json ContentType.
type AddGroupMemberJSONRequestBody = GroupMemberCreateRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectCreateRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = ProjectUpdateRequest

// AddProjectGroupJSONRequestBody defines body for AddProjectGroup for application/json ContentType.
type AddProjectGroupJSONRequestBody = ProjectGroupCreateRequest

// UpdateProjectGroupJSONRequestBody defines body for UpdateProjectGroup for application/json ContentType.
type UpdateProjectGroupJSONRequestBody = ProjectGroupUpdateRequest

// CreateStoryJSONRequestBody defines body for CreateStory for application/json ContentType.
type CreateStoryJSONRequestBody = StoryCreateRequest

// CreateTicketJSONRequestBody defines body for CreateTicket for application/json ContentType.
type CreateTicketJSONRequestBody = TicketCreateRequest

// CreateWebhookJSONRequestBody defines body for CreateWebhook for application/json ContentType.
type CreateWebhookJSONRequestBody = WebhookCreateRequest

// UpdateWebhookJSONRequestBody defines body for UpdateWebhook for application/json ContentType.
type UpdateWebhookJSONRequestBody = WebhookUpdateRequest

// TestWebhookJSONRequestBody defines body for TestWebhook for application/json ContentType.
type TestWebhookJSONRequestBody = WebhookTestRequest

// UpdateWorkflowJSONRequestBody defines body for UpdateWorkflow for application/json ContentType.
type UpdateWorkflowJSONRequestBody = WorkflowUpdateRequest

// UpdateStoryJSONRequestBody defines body for UpdateStory for application/json ContentType.
type UpdateStoryJSONRequestBody = StoryUpdateRequest

// UpdateTicketJSONRequestBody defines body for UpdateTicket for application/json ContentType.
type UpdateTicketJSONRequestBody = TicketUpdateRequest

// AddTicketCommentJSONRequestBody defines body for AddTicketComment for application/json ContentType.
type AddTicketCommentJSONRequestBody = TicketCommentCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Sync all Keycloak users to database
	// (POST /admin/sync-users)
	SyncUsers(w http.ResponseWriter, r *http.Request)
	// Login
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Current user
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// List groups
	// (GET /groups)
	ListGroups(w http.ResponseWriter, r *http.Request)
	// Create group
	// (POST /groups)
	CreateGroup(w http.ResponseWriter, r *http.Request)
	// Delete group
	// (DELETE /groups/{groupId})
	DeleteGroup(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID)
	// Get group
	// (GET /groups/{groupId})
	GetGroup(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID)
	// Update group
	// (PATCH /groups/{groupId})
	UpdateGroup(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID)
	// List group members
	// (GET /groups/{groupId}/members)
	ListGroupMembers(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID)
	// Add user to group
	// (POST /groups/{groupId}/members)
	AddGroupMember(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID)
	// Remove user from group
	// (DELETE /groups/{groupId}/members/{userId})
	DeleteGroupMember(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID, userId openapi_types.UUID)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// List projects
	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request)
	// Create project
	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// Delete project
	// (DELETE /projects/{projectId})
	DeleteProject(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Get project
	// (GET /projects/{projectId})
	GetProject(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Update project
	// (PATCH /projects/{projectId})
	UpdateProject(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Kanban board snapshot
	// (GET /projects/{projectId}/board)
	GetBoard(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// List project groups
	// (GET /projects/{projectId}/groups)
	ListProjectGroups(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Add group to project
	// (POST /projects/{projectId}/groups)
	AddProjectGroup(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Remove group from project
	// (DELETE /projects/{projectId}/groups/{groupId})
	DeleteProjectGroup(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, groupId openapi_types.UUID)
	// Update project group role
	// (PATCH /projects/{projectId}/groups/{groupId})
	UpdateProjectGroup(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, groupId openapi_types.UUID)
	// List stories
	// (GET /projects/{projectId}/stories)
	ListStories(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Create story
	// (POST /projects/{projectId}/stories)
	CreateStory(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// List tickets for project
	// (GET /projects/{projectId}/tickets)
	ListTickets(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, params ListTicketsParams)
	// Create ticket
	// (POST /projects/{projectId}/tickets)
	CreateTicket(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// List webhooks
	// (GET /projects/{projectId}/webhooks)
	ListWebhooks(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Create webhook
	// (POST /projects/{projectId}/webhooks)
	CreateWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Delete webhook
	// (DELETE /projects/{projectId}/webhooks/{id})
	DeleteWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, id openapi_types.UUID)
	// Get webhook
	// (GET /projects/{projectId}/webhooks/{id})
	GetWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, id openapi_types.UUID)
	// Update webhook
	// (PATCH /projects/{projectId}/webhooks/{id})
	UpdateWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, id openapi_types.UUID)
	// Send test webhook
	// (POST /projects/{projectId}/webhooks/{id}/test)
	TestWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, id openapi_types.UUID)
	// Get workflow states
	// (GET /projects/{projectId}/workflow)
	GetWorkflow(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Update workflow states
	// (PUT /projects/{projectId}/workflow)
	UpdateWorkflow(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Delete story
	// (DELETE /stories/{id})
	DeleteStory(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get story
	// (GET /stories/{id})
	GetStory(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update story
	// (PATCH /stories/{id})
	UpdateStory(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Delete ticket
	// (DELETE /tickets/{id})
	DeleteTicket(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get ticket
	// (GET /tickets/{id})
	GetTicket(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update ticket
	// (PATCH /tickets/{id})
	UpdateTicket(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List ticket comments
	// (GET /tickets/{id}/comments)
	ListTicketComments(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Add ticket comment
	// (POST /tickets/{id}/comments)
	AddTicketComment(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Delete ticket comment
	// (DELETE /tickets/{id}/comments/{commentId})
	DeleteTicketComment(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, commentId openapi_types.UUID)
	// List users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Sync all Keycloak users to database
// (POST /admin/sync-users)
func (_ Unimplemented) SyncUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Current user
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List groups
// (GET /groups)
func (_ Unimplemented) ListGroups(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create group
// (POST /groups)
func (_ Unimplemented) CreateGroup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete group
// (DELETE /groups/{groupId})
func (_ Unimplemented) DeleteGroup(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get group
// (GET /groups/{groupId})
func (_ Unimplemented) GetGroup(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update group
// (PATCH /groups/{groupId})
func (_ Unimplemented) UpdateGroup(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List group members
// (GET /groups/{groupId}/members)
func (_ Unimplemented) ListGroupMembers(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add user to group
// (POST /groups/{groupId}/members)
func (_ Unimplemented) AddGroupMember(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove user from group
// (DELETE /groups/{groupId}/members/{userId})
func (_ Unimplemented) DeleteGroupMember(w http.ResponseWriter, r *http.Request, groupId openapi_types.UUID, userId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List projects
// (GET /projects)
func (_ Unimplemented) ListProjects(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create project
// (POST /projects)
func (_ Unimplemented) CreateProject(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete project
// (DELETE /projects/{projectId})
func (_ Unimplemented) DeleteProject(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get project
// (GET /projects/{projectId})
func (_ Unimplemented) GetProject(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update project
// (PATCH /projects/{projectId})
func (_ Unimplemented) UpdateProject(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Kanban board snapshot
// (GET /projects/{projectId}/board)
func (_ Unimplemented) GetBoard(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List project groups
// (GET /projects/{projectId}/groups)
func (_ Unimplemented) ListProjectGroups(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add group to project
// (POST /projects/{projectId}/groups)
func (_ Unimplemented) AddProjectGroup(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove group from project
// (DELETE /projects/{projectId}/groups/{groupId})
func (_ Unimplemented) DeleteProjectGroup(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, groupId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update project group role
// (PATCH /projects/{projectId}/groups/{groupId})
func (_ Unimplemented) UpdateProjectGroup(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, groupId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List stories
// (GET /projects/{projectId}/stories)
func (_ Unimplemented) ListStories(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create story
// (POST /projects/{projectId}/stories)
func (_ Unimplemented) CreateStory(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List tickets for project
// (GET /projects/{projectId}/tickets)
func (_ Unimplemented) ListTickets(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, params ListTicketsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create ticket
// (POST /projects/{projectId}/tickets)
func (_ Unimplemented) CreateTicket(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List webhooks
// (GET /projects/{projectId}/webhooks)
func (_ Unimplemented) ListWebhooks(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create webhook
// (POST /projects/{projectId}/webhooks)
func (_ Unimplemented) CreateWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete webhook
// (DELETE /projects/{projectId}/webhooks/{id})
func (_ Unimplemented) DeleteWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get webhook
// (GET /projects/{projectId}/webhooks/{id})
func (_ Unimplemented) GetWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update webhook
// (PATCH /projects/{projectId}/webhooks/{id})
func (_ Unimplemented) UpdateWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send test webhook
// (POST /projects/{projectId}/webhooks/{id}/test)
func (_ Unimplemented) TestWebhook(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get workflow states
// (GET /projects/{projectId}/workflow)
func (_ Unimplemented) GetWorkflow(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update workflow states
// (PUT /projects/{projectId}/workflow)
func (_ Unimplemented) UpdateWorkflow(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete story
// (DELETE /stories/{id})
func (_ Unimplemented) DeleteStory(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get story
// (GET /stories/{id})
func (_ Unimplemented) GetStory(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update story
// (PATCH /stories/{id})
func (_ Unimplemented) UpdateStory(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete ticket
// (DELETE /tickets/{id})
func (_ Unimplemented) DeleteTicket(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get ticket
// (GET /tickets/{id})
func (_ Unimplemented) GetTicket(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update ticket
// (PATCH /tickets/{id})
func (_ Unimplemented) UpdateTicket(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List ticket comments
// (GET /tickets/{id}/comments)
func (_ Unimplemented) ListTicketComments(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add ticket comment
// (POST /tickets/{id}/comments)
func (_ Unimplemented) AddTicketComment(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete ticket comment
// (DELETE /tickets/{id}/comments/{commentId})
func (_ Unimplemented) DeleteTicketComment(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, commentId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SyncUsers operation middleware
func (siw *ServerInterfaceWrapper) SyncUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroups(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroup(w, r, groupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, groupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGroup(w, r, groupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroupMembers operation middleware
func (siw *ServerInterfaceWrapper) ListGroupMembers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroupMembers(w, r, groupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddGroupMember operation middleware
func (siw *ServerInterfaceWrapper) AddGroupMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddGroupMember(w, r, groupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroupMember operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroupMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroupMember(w, r, groupId, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProject operation middleware
func (siw *ServerInterfaceWrapper) DeleteProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBoard operation middleware
func (siw *ServerInterfaceWrapper) GetBoard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBoard(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectGroups operation middleware
func (siw *ServerInterfaceWrapper) ListProjectGroups(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectGroups(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddProjectGroup operation middleware
func (siw *ServerInterfaceWrapper) AddProjectGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddProjectGroup(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProjectGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteProjectGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProjectGroup(w, r, projectId, groupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProjectGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateProjectGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProjectGroup(w, r, projectId, groupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListStories operation middleware
func (siw *ServerInterfaceWrapper) ListStories(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListStories(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateStory operation middleware
func (siw *ServerInterfaceWrapper) CreateStory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateStory(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTickets operation middleware
func (siw *ServerInterfaceWrapper) ListTickets(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketsParams

	// ------------- Optional query parameter "stateId" -------------

	err = runtime.BindQueryParameter("form", true, false, "stateId", r.URL.Query(), &params.StateId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "stateId", Err: err})
		return
	}

	// ------------- Optional query parameter "assigneeId" -------------

	err = runtime.BindQueryParameter("form", true, false, "assigneeId", r.URL.Query(), &params.AssigneeId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assigneeId", Err: err})
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTickets(w, r, projectId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTicket operation middleware
func (siw *ServerInterfaceWrapper) CreateTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTicket(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWebhooks operation middleware
func (siw *ServerInterfaceWrapper) ListWebhooks(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWebhooks(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWebhook operation middleware
func (siw *ServerInterfaceWrapper) CreateWebhook(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWebhook(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWebhook operation middleware
func (siw *ServerInterfaceWrapper) DeleteWebhook(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWebhook(w, r, projectId, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWebhook operation middleware
func (siw *ServerInterfaceWrapper) GetWebhook(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWebhook(w, r, projectId, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWebhook operation middleware
func (siw *ServerInterfaceWrapper) UpdateWebhook(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWebhook(w, r, projectId, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TestWebhook operation middleware
func (siw *ServerInterfaceWrapper) TestWebhook(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TestWebhook(w, r, projectId, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWorkflow operation middleware
func (siw *ServerInterfaceWrapper) GetWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkflow(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWorkflow operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkflow(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", chi.URLParam(r, "projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWorkflow(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteStory operation middleware
func (siw *ServerInterfaceWrapper) DeleteStory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteStory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStory operation middleware
func (siw *ServerInterfaceWrapper) GetStory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateStory operation middleware
func (siw *ServerInterfaceWrapper) UpdateStory(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateStory(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTicket operation middleware
func (siw *ServerInterfaceWrapper) DeleteTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicket operation middleware
func (siw *ServerInterfaceWrapper) GetTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTicket operation middleware
func (siw *ServerInterfaceWrapper) UpdateTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTicketComments operation middleware
func (siw *ServerInterfaceWrapper) ListTicketComments(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTicketComments(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTicketComment operation middleware
func (siw *ServerInterfaceWrapper) AddTicketComment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTicketComment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTicketComment operation middleware
func (siw *ServerInterfaceWrapper) DeleteTicketComment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "commentId" -------------
	var commentId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "commentId", chi.URLParam(r, "commentId"), &commentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "commentId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTicketComment(w, r, id, commentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/sync-users", wrapper.SyncUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups", wrapper.ListGroups)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups", wrapper.CreateGroup)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/groups/{groupId}", wrapper.DeleteGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups/{groupId}", wrapper.GetGroup)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/groups/{groupId}", wrapper.UpdateGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups/{groupId}/members", wrapper.ListGroupMembers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups/{groupId}/members", wrapper.AddGroupMember)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/groups/{groupId}/members/{userId}", wrapper.DeleteGroupMember)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects", wrapper.ListProjects)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects", wrapper.CreateProject)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/projects/{projectId}", wrapper.DeleteProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}", wrapper.GetProject)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/projects/{projectId}", wrapper.UpdateProject)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/board", wrapper.GetBoard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/groups", wrapper.ListProjectGroups)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/groups", wrapper.AddProjectGroup)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/projects/{projectId}/groups/{groupId}", wrapper.DeleteProjectGroup)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/projects/{projectId}/groups/{groupId}", wrapper.UpdateProjectGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/stories", wrapper.ListStories)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/stories", wrapper.CreateStory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/tickets", wrapper.ListTickets)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/tickets", wrapper.CreateTicket)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/webhooks", wrapper.ListWebhooks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/webhooks", wrapper.CreateWebhook)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/projects/{projectId}/webhooks/{id}", wrapper.DeleteWebhook)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/webhooks/{id}", wrapper.GetWebhook)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/projects/{projectId}/webhooks/{id}", wrapper.UpdateWebhook)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/projects/{projectId}/webhooks/{id}/test", wrapper.TestWebhook)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/projects/{projectId}/workflow", wrapper.GetWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/projects/{projectId}/workflow", wrapper.UpdateWorkflow)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/stories/{id}", wrapper.DeleteStory)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/stories/{id}", wrapper.GetStory)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/stories/{id}", wrapper.UpdateStory)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/tickets/{id}", wrapper.DeleteTicket)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tickets/{id}", wrapper.GetTicket)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/tickets/{id}", wrapper.UpdateTicket)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tickets/{id}/comments", wrapper.ListTicketComments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tickets/{id}/comments", wrapper.AddTicketComment)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/tickets/{id}/comments/{commentId}", wrapper.DeleteTicketComment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})

	return r
}
